name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod a+w /srv/jekyll/Gemfile.lock && chmod 777 /srv/jekyll && jekyll build --future"
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: lx49.hoststar.hosting
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        port: 21
        protocol: ftp
        server-dir: /home/ch73732/web/luca.furrer-haab.ch/public_html/
        local-dir: ${{ github.workspace }}/_site/
        state-name: ../.ftp-deploy-sync-state.json
        log-level: verbose